namespace SLK_Model
{
    /// <summary>
    /// 입고_메인 테이블
    /// </summary>
    public class ReceivingMaster_Model
    {
        public string 센터코드 { get; set; }                     // 센터코드 (char(5))
        public string B코드 { get; set; }                       // B코드 (char(2))
        public string 창고코드 { get; set; }                     // 창고코드 (varchar(20))
        public string 전표구분 { get; set; }                     // 전표구분 (char(2))
        public string 등록일자 { get; set; }                     // 등록일자 (char(8))
        public int 순번 { get; set; }                           // 순번 (int)
        public string 생산처코드 { get; set; }                   // 생산처코드 (varchar(20))
        public string 상품코드 { get; set; }                     // 상품코드 (varchar(60))
        public string 상품구분 { get; set; }                     // 상품구분 (char(1))
        public int 의뢰수량 { get; set; }                        // 의뢰수량 (int)
        public int 주문수량 { get; set; }                        // 주문수량 (int)
        public int 작업수량 { get; set; }                        // 작업수량 (int)
        public int 수불수량 { get; set; }                        // 수불수량 (int)
        public float 단가1 { get; set; }                        // 단가1 (float)
        public float 단가2 { get; set; }                        // 단가2 (float)
        public string 주문일자 { get; set; }                     // 주문일자 (char(8))
        public string 예정일자 { get; set; }                     // 예정일자 (char(8))
        public string 수불일자 { get; set; }                     // 수불일자 (char(8))
        public string? 차수 { get; set; }                        // 차수 (varchar(5), nullable)
        public string WMS전표번호 { get; set; }                  // WMS전표번호 (char(15))
        public string? 브랜드전표번호 { get; set; }               // 브랜드전표번호 (varchar(30), nullable)
        public string? 브랜드삭제키 { get; set; }                 // 브랜드삭제키 (varchar(30), nullable)
        public string? BL번호 { get; set; }                     // BL번호 (varchar(50), nullable)
        public string 작업구분 { get; set; }                     // 작업구분 (varchar(5))
        public string 입력구분 { get; set; }                     // 입력구분 (varchar(5))
        public string 입력사유 { get; set; }                     // 입력사유 (varchar(50))
        public string? 비고 { get; set; }                       // 비고 (varchar(50), nullable)
        public string? 작지번호 { get; set; }                   // 작지번호 (char(13), nullable)
        public string? 브랜드키1 { get; set; }                   // 브랜드키1 (varchar(50), nullable)
        public string? 브랜드키2 { get; set; }                   // 브랜드키2 (varchar(50), nullable)
        public string 입고방법 { get; set; }                     // 입고방법 (varchar(5))
        public string 입고유형 { get; set; }                     // 입고유형 (varchar(5))
        public string 양불구분 { get; set; }                     // 양불구분 (varchar(5))
        public string 불량유형 { get; set; }                     // 불량유형 (varchar(5))
        public string 예비구분1 { get; set; }                   // 예비구분1 (varchar(5))
        public string 예비구분2 { get; set; }                   // 예비구분2 (varchar(5))
        public bool 예비구분3 { get; set; }                      // 예비구분3 (bit)
        public bool 예비구분4 { get; set; }                      // 예비구분4 (bit)
        public string 상태구분 { get; set; }                     // 상태구분 (char(1))
        public DateTime 등록일시 { get; set; }                   // 등록일시 (datetime)
        public string 등록자 { get; set; }                       // 등록자 (varchar(20))
        public string 등록자주소 { get; set; }                   // 등록자주소 (varchar(20))
        public string 등록자맥주소 { get; set; }                 // 등록자맥주소 (char(17))
        public DateTime? 수정일시 { get; set; }                  // 수정일시 (datetime, nullable)
        public string? 수정자 { get; set; }                     // 수정자 (varchar(20), nullable)
        public string? 수정자주소 { get; set; }                 // 수정자주소 (varchar(20), nullable)
        public string? 수정자맥주소 { get; set; }               // 수정자맥주소 (char(17), nullable)
        public DateTime? 확정일시 { get; set; }                  // 확정일시 (datetime, nullable)
        public string? 확정자 { get; set; }                     // 확정자 (varchar(20), nullable)
        public string? 확정자주소 { get; set; }                 // 확정자주소 (varchar(20), nullable)
        public string? 확정자맥주소 { get; set; }               // 확정자맥주소 (char(17), nullable)
        public string? 공정코드1 { get; set; }                  // 공정코드1 (char(5), nullable)
        public string? 공정코드2 { get; set; }                  // 공정코드2 (char(5), nullable)
        public string? 공정코드3 { get; set; }                  // 공정코드3 (char(5), nullable)
        public string? 사업부코드 { get; set; }                 // 사업부코드 (varchar(20), nullable)
        public string? 품번차수 { get; set; }                   // 품번차수 (varchar(50), nullable)
        public string? 지시번호 { get; set; }                   // 지시번호 (varchar(30), nullable)
        public string? HOSTKEY1 { get; set; }                   // HOSTKEY1 (varchar(255), nullable)
        public string? HOSTKEY2 { get; set; }                   // HOSTKEY2 (varchar(255), nullable)
        public string? HOSTKEY3 { get; set; }                   // HOSTKEY3 (varchar(255), nullable)
        public string? HOSTKEY4 { get; set; }                   // HOSTKEY4 (varchar(255), nullable)
        public string? HOSTKEY5 { get; set; }                   // HOSTKEY5 (varchar(255), nullable)
        public string? HOSTKEY6 { get; set; }                   // HOSTKEY6 (varchar(255), nullable)
        public string? 원산지코드 { get; set; }                 // 원산지코드 (varchar(5), nullable)
        public string? 호스트지시마스터값 { get; set; }         // 호스트지시마스터값 (varchar(100), nullable)
        public string? 호스트지시디테일값 { get; set; }         // 호스트지시디테일값 (varchar(100), nullable)
        public string? 호스트실적마스터값 { get; set; }         // 호스트실적마스터값 (varchar(100), nullable)
        public string? 호스트실적디테일값 { get; set; }         // 호스트실적디테일값 (varchar(100), nullable)
        public int? 연계키아이디 { get; set; }                  // 연계키아이디 (int, nullable)
        public string? 발주연계여부 { get; set; }               // 발주연계여부 (char(1), nullable)
        public string? EXT_COLUMN1 { get; set; }                // EXT_COLUMN1 (varchar(255), nullable)
        public string? EXT_COLUMN2 { get; set; }                // EXT_COLUMN2 (varchar(255), nullable)
        public int? EXT_COLUMN3 { get; set; }                   // EXT_COLUMN3 (int, nullable)
        public string? EXT_COLUMN4 { get; set; }                // EXT_COLUMN4 (varchar(255), nullable)
        public string? EXT_COLUMN5 { get; set; }                // EXT_COLUMN5 (varchar(255), nullable)
        public int? EXT_COLUMN6 { get; set; }                   // EXT_COLUMN6 (int, nullable)
        public string? 원전표번호 { get; set; }                 // 원전표번호 (char(15), nullable)
        public bool? 정산제외여부 { get; set; }                 // 정산제외여부 (bit, nullable)
    }
}